"""
Utilities for loading baked clip keypoint sequences and computing clip similarity.
The baked keypoints are generated by tools/bake_clips.mjs which renders each
Mixamo clip at a canonical front-facing camera and exports joint screen positions.
"""
import json
import numpy as np

from modal_app.pipeline.dataset import JOINT_ORDER

# Canonical render resolution used in bake_clips.mjs
RENDER_W = 1280
RENDER_H = 720


def load_baked_clip_keypoints(path: str) -> tuple[np.ndarray, list[str]]:
    """
    Load baked clip keypoint sequences from bake_clips.mjs JSON output.

    Returns:
        keypoints: [N_clips, 60, 6, 2] float32, normalized to [-1, 1]
        clip_names: [N_clips] list of normalized clip name strings
    """
    with open(path) as f:
        data = json.load(f)

    names = [d["name"] for d in data]
    kps_list = []

    for clip in data:
        frames = clip["keypoints"]  # list of up to 60 frame dicts
        clip_arr = np.zeros((60, 6, 2), dtype=np.float32)
        for fi, frame in enumerate(frames[:60]):
            for ji, joint in enumerate(JOINT_ORDER):
                val = frame.get(joint)
                if val is not None and len(val) >= 2:
                    clip_arr[fi, ji, 0] = float(val[0])
                    clip_arr[fi, ji, 1] = float(val[1])
        # Normalize pixel coords to [-1, 1] to match dataset.normalize_keypoints
        clip_arr[:, :, 0] = (clip_arr[:, :, 0] / RENDER_W) * 2 - 1
        clip_arr[:, :, 1] = (clip_arr[:, :, 1] / RENDER_H) * 2 - 1
        kps_list.append(np.clip(clip_arr, -1.0, 1.0))

    return np.stack(kps_list), names  # [N_clips, 60, 6, 2]


def compute_clip_similarity(
    observed_kp: np.ndarray,    # [60, 6, 2]
    reference_kps: np.ndarray,  # [N_clips, 60, 6, 2]
) -> np.ndarray:                # [N_clips] cosine similarities in [-1, 1]
    """Cosine similarity between observed motion and each reference clip."""
    obs_flat = observed_kp.flatten()
    ref_flat = reference_kps.reshape(len(reference_kps), -1)
    obs_norm = obs_flat / (np.linalg.norm(obs_flat) + 1e-8)
    ref_norm = ref_flat / (np.linalg.norm(ref_flat, axis=1, keepdims=True) + 1e-8)
    return ref_norm @ obs_norm
