"""Cross-language contract test for the director runner.

tests/animus_bridge/fixtures/director_requests.json is generated by the
JS mapper:

    node scripts/animus-director.mjs --fallback-only --voice-mode convert \
        --emit-requests --line "Wave to the viewer and say hello." \
        --speech "Hello, I am K-VRC." > tests/animus_bridge/fixtures/director_requests.json

This test replays that committed fixture through the real bridge
validation and operations against the fake scene built from the
embodiment profile, proving the mapper's output satisfies the Python
contract byte for byte: every request validates, every take lands, and
nothing references a bone or shape key the profile does not declare.
"""

import json
import os
import unittest

import _bootstrap  # noqa: F401
import fake_bpy

from animus_bridge import operations, protocol

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
FIXTURE = os.path.join(HERE, "fixtures", "director_requests.json")
PROFILE = os.path.join(
    REPO, "src", "animus", "embodiment", "kvrc-testrig.profile.json"
)


def load_json(path):
    with open(path, "r", encoding="utf-8-sig") as handle:
        return json.load(handle)


class DirectorRequestTest(unittest.TestCase):
    def setUp(self):
        fake_bpy.reset()
        self.profile = load_json(PROFILE)
        rig = self.profile["rig"]
        fake_bpy.add_armature_object(rig["object"], rig["bones"])
        fake_bpy.add_shape_keyed_object(
            rig["face_object"], ["Basis"] + rig["shape_keys"]
        )
        self.fixture = load_json(FIXTURE)

    def execute(self, request):
        request_id, op, raw_params = protocol.validate_envelope(request)
        params = protocol.validate_params(op, raw_params)
        return op, operations.HANDLERS[op](params)

    def test_fixture_names_the_committed_profile(self):
        self.assertEqual(
            self.fixture["profile"],
            {
                "name": self.profile["profile"],
                "version": self.profile["profile_version"],
            },
        )

    def test_every_mapped_request_validates_and_lands(self):
        self.assertEqual(len(self.fixture["requests"]), 4)
        receipts = []
        for request in self.fixture["requests"]:
            op, receipt = self.execute(request)
            receipts.append((op, receipt))
            self.assertIn(receipt["action"], fake_bpy.data.actions.keys())

        ops = [op for op, _ in receipts]
        self.assertEqual(
            ops, ["perform_take", "perform_take", "apply_shape_keys", "apply_shape_keys"]
        )

        # One Action and one NLA strip per layer, on the right datablock.
        self.assertEqual(len(fake_bpy.data.actions), 4)
        kvrc = fake_bpy.data.objects.get(self.profile["rig"]["object"])
        face_key = fake_bpy.data.objects.get(
            self.profile["rig"]["face_object"]
        ).data.shape_keys
        self.assertEqual(len(kvrc.animation_data.nla_tracks), 2)
        self.assertEqual(len(face_key.animation_data.nla_tracks), 2)

        # Distinct names, nothing overwritten.
        names = [receipt["action"] for _, receipt in receipts]
        self.assertEqual(len(names), len(set(names)))

    def test_pose_samples_only_reference_profile_bones(self):
        bones = set(self.profile["rig"]["bones"])
        for request in self.fixture["requests"]:
            if request["op"] != "perform_take":
                continue
            for sample in request["params"]["samples"]:
                self.assertIn(sample["bone"], bones)

    def test_shape_samples_only_reference_profile_shape_keys(self):
        keys = set(self.profile["rig"]["shape_keys"])
        for request in self.fixture["requests"]:
            if request["op"] != "apply_shape_keys":
                continue
            for sample in request["params"]["samples"]:
                self.assertIn(sample["shape_key"], keys)
                self.assertGreaterEqual(sample["weight"], 0.0)
                self.assertLessEqual(sample["weight"], 1.0)

    def test_tampered_request_is_refused_and_mutates_nothing(self):
        request = json.loads(json.dumps(self.fixture["requests"][0]))
        request["params"]["samples"][0]["bone"] = "tentacle.R"
        request_id, op, raw_params = protocol.validate_envelope(request)
        params = protocol.validate_params(op, raw_params)
        with self.assertRaises(protocol.Refusal) as caught:
            operations.HANDLERS[op](params)
        self.assertEqual(caught.exception.code, protocol.UNKNOWN_BONE)
        self.assertEqual(len(fake_bpy.data.actions), 0)


if __name__ == "__main__":
    unittest.main()
