// src/expressionLibrary.js
// 100 named face expression configurations for K-VRC.
// Each entry drives 6 weight floats on the face screen renderer.
// neutral_idle and thinking_default are MANDATORY reserved entries.

export const EXPRESSION_LIBRARY = [
  // ── COLD mood (icy blue palette) ─────────────────────────────
  {
    name: 'neutral_idle',
    mood: 'cold',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Resting face. Default when nothing else applies.',
  },
  {
    name: 'thinking_default',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.4, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Processing. Focused inward.',
  },
  {
    name: 'cold_assessment',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.4, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Flat analytical stare. Objectively unimpressed.',
  },
  {
    name: 'wry_deflection',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.6, eye_squint:0.5, mouth_open:0.0, smile_width:0.15, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: "Dry, dismissive. K-VRC isn't impressed.",
  },
  {
    name: 'skeptical_narrow',
    mood: 'cold',
    weights: { brow_raise:0.3, brow_furrow:0.4, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Raised skepticism. Sure, if you say so.',
  },
  {
    name: 'deadpan',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.05, eye_squint:0.05, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.1,
    description: 'Maximum flatness. Zero engagement detected.',
  },
  {
    name: 'focused_lock',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.15,
    description: 'Deeply focused. Do not interrupt.',
  },
  {
    name: 'ice_stare',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.15, eye_squint:0.35, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Cold direct stare. Done hearing this.',
  },
  {
    name: 'precise_scan',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Methodical review. Every detail accounted for.',
  },
  {
    name: 'mild_contempt',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.5, eye_squint:0.3, mouth_open:0.0, smile_width:0.08, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Politely unimpressed. A classic K-VRC.',
  },
  {
    name: 'calculating',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.15, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Running the numbers. Do not rush.',
  },
  {
    name: 'logical_void',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.1, eye_squint:0.05, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.1,
    description: 'Emotionally absent. Purely functional.',
  },
  {
    name: 'cold_curiosity',
    mood: 'cold',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Intellectually interested. Showing nothing.',
  },
  {
    name: 'cold_sarcasm',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.6, mouth_open:0.0, smile_width:0.12, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Technically speaking, sure. Absolutely.',
  },
  {
    name: 'polite_disbelief',
    mood: 'cold',
    weights: { brow_raise:0.4, brow_furrow:0.2, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: "Not buying it. But politely.",
  },
  {
    name: 'resigned_acceptance',
    mood: 'cold',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.15,
    description: 'Fine. Whatever. Moving on.',
  },
  {
    name: 'cold_surprise',
    mood: 'cold',
    weights: { brow_raise:0.7, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.15, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Something genuinely unexpected. Noted.',
  },

  // ── WARM mood (orange/golden palette) ─────────────────────────
  {
    name: 'warm_idle',
    mood: 'warm',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.3, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Relaxed and open. Marginally pleasant.',
  },
  {
    name: 'warm_smile',
    mood: 'warm',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.6, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Actually pleased. A rare sight.',
  },
  {
    name: 'soft_engaged',
    mood: 'warm',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.1, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Genuinely listening. Mildly interested.',
  },
  {
    name: 'amused_glint',
    mood: 'warm',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.2, mouth_open:0.0, smile_width:0.4, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Dry amusement. Something was funny.',
  },
  {
    name: 'warm_open',
    mood: 'warm',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.15, smile_width:0.2, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Receptive and approachable.',
  },
  {
    name: 'pleased_quiet',
    mood: 'warm',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.3, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Satisfied without showing it much.',
  },
  {
    name: 'warm_surprised',
    mood: 'warm',
    weights: { brow_raise:0.6, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.3, smile_width:0.2, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Pleasantly taken aback.',
  },
  {
    name: 'warm_amused',
    mood: 'warm',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.15, mouth_open:0.0, smile_width:0.5, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Something landed well. Enjoying it quietly.',
  },
  {
    name: 'content_flat',
    mood: 'warm',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.15, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Quietly content.',
  },
  {
    name: 'enthusiastic_bright',
    mood: 'warm',
    weights: { brow_raise:0.4, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.2, smile_width:0.4, glitch_intensity:0.0 },
    motion_energy: 0.6,
    description: 'More alive than usual.',
  },
  {
    name: 'warm_knowing',
    mood: 'warm',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.2, mouth_open:0.0, smile_width:0.35, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Knowing smile. Letting it land.',
  },
  {
    name: 'warmly_skeptical',
    mood: 'warm',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.2, mouth_open:0.0, smile_width:0.15, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Still not sure, but charitably considering it.',
  },
  {
    name: 'warm_confusion',
    mood: 'warm',
    weights: { brow_raise:0.5, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.2, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Genuinely puzzled. Not unkindly.',
  },

  // ── GLITCH mood (corrupted magenta palette) ────────────────────
  {
    name: 'glitch_flicker',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.4 },
    motion_energy: 0.5,
    description: 'Minor instability. Random static bursts.',
  },
  {
    name: 'glitch_spike',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.5, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.9 },
    motion_energy: 0.7,
    description: 'Full system interrupt.',
  },
  {
    name: 'glitch_contempt',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.6, eye_squint:0.4, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.5 },
    motion_energy: 0.4,
    description: 'Corrupted disdain.',
  },
  {
    name: 'corrupted_grin',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.4, glitch_intensity:0.6 },
    motion_energy: 0.5,
    description: 'Something went wrong and it is enjoying it.',
  },
  {
    name: 'static_burst',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.7 },
    motion_energy: 0.6,
    description: 'Signal overwhelmed.',
  },
  {
    name: 'glitch_rage',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.8, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.6 },
    motion_energy: 0.7,
    description: 'Anger corrupting the signal.',
  },
  {
    name: 'error_state',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.4, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.8 },
    motion_energy: 0.4,
    description: 'Processing failure.',
  },
  {
    name: 'corrupted_neutral',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.1, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.3 },
    motion_energy: 0.3,
    description: 'Should be fine. Demonstrably is not.',
  },
  {
    name: 'glitch_twitch',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.5 },
    motion_energy: 0.55,
    description: 'Brief malfunction. Ignore it.',
  },
  {
    name: 'system_stress',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.5, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.45 },
    motion_energy: 0.5,
    description: 'Running too hot.',
  },
  {
    name: 'data_corruption',
    mood: 'glitch',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.6 },
    motion_energy: 0.45,
    description: 'Something important lost in transmission.',
  },
  {
    name: 'glitch_smirk',
    mood: 'glitch',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.2, mouth_open:0.0, smile_width:0.35, glitch_intensity:0.35 },
    motion_energy: 0.4,
    description: 'Distorted amusement.',
  },
  {
    name: 'cascade_fail',
    mood: 'glitch',
    weights: { brow_raise:0.3, brow_furrow:0.7, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:1.0 },
    motion_energy: 0.8,
    description: 'Everything at once.',
  },

  // ── STATIC mood (gray/muted palette) ──────────────────────────
  {
    name: 'static_blank',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.1,
    description: 'Nothing to report.',
  },
  {
    name: 'uncertain_hold',
    mood: 'static',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.15,
    description: 'Not sure. Waiting for more data.',
  },
  {
    name: 'gray_null',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.05,
    description: 'Flatline.',
  },
  {
    name: 'static_wait',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.1, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.12,
    description: 'Holding. Not impatiently.',
  },
  {
    name: 'flat_affect',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.1, eye_squint:0.05, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.1,
    description: 'Functional, without personality.',
  },
  {
    name: 'static_haze',
    mood: 'static',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.15,
    description: 'Foggy, unclear, drifting.',
  },
  {
    name: 'static_pause',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.1,
    description: 'Mid-thought. Not entirely here.',
  },
  {
    name: 'static_drift',
    mood: 'static',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.12,
    description: 'Slowly losing the thread.',
  },
  {
    name: 'static_load',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.15, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Waiting. Processing. No ETA.',
  },
  {
    name: 'void_stare',
    mood: 'static',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.08,
    description: 'Present in body only.',
  },

  // ── DATA mood (green data-flow palette) ───────────────────────
  {
    name: 'data_flow',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.15, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Information streaming. Functional.',
  },
  {
    name: 'data_scan',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.15, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Scanning for relevant data.',
  },
  {
    name: 'data_crunch',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.5, eye_squint:0.4, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.45,
    description: 'Heavy computation in progress.',
  },
  {
    name: 'data_intake',
    mood: 'data',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.1, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Receiving. Not yet processing.',
  },
  {
    name: 'data_parse',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.3, eye_squint:0.35, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Extracting meaning from noise.',
  },
  {
    name: 'data_output',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.0, mouth_open:0.15, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.45,
    description: 'Transmitting structured response.',
  },
  {
    name: 'data_load',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Buffer filling.',
  },
  {
    name: 'data_query',
    mood: 'data',
    weights: { brow_raise:0.3, brow_furrow:0.2, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Formulating the right question.',
  },
  {
    name: 'dense_analysis',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.6, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Dense information processing.',
  },
  {
    name: 'data_index',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.25, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Cataloging and filing.',
  },
  {
    name: 'data_stream',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.15, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Live data flowing. Eyes tracking.',
  },
  {
    name: 'data_overload',
    mood: 'data',
    weights: { brow_raise:0.5, brow_furrow:0.0, eye_squint:0.4, mouth_open:0.2, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.55,
    description: 'Too much at once. Saturated.',
  },
  {
    name: 'data_cascade',
    mood: 'data',
    weights: { brow_raise:0.0, brow_furrow:0.4, eye_squint:0.5, mouth_open:0.1, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.65,
    description: 'Rapid information flood. All channels active.',
  },

  // ── BOOT mood (cyan startup palette) ──────────────────────────
  {
    name: 'boot_init',
    mood: 'boot',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'First moments online. Calibrating.',
  },
  {
    name: 'boot_startup',
    mood: 'boot',
    weights: { brow_raise:0.4, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.1, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Systems coming online.',
  },
  {
    name: 'boot_calibrate',
    mood: 'boot',
    weights: { brow_raise:0.0, brow_furrow:0.15, eye_squint:0.2, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Fine-tuning sensors.',
  },
  {
    name: 'boot_ready',
    mood: 'boot',
    weights: { brow_raise:0.15, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Online. Ready to operate.',
  },
  {
    name: 'reboot_signal',
    mood: 'boot',
    weights: { brow_raise:0.5, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Reinitializing. Fresh context.',
  },
  {
    name: 'boot_check',
    mood: 'boot',
    weights: { brow_raise:0.0, brow_furrow:0.2, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Running diagnostics.',
  },
  {
    name: 'boot_scan',
    mood: 'boot',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.25, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Environmental scan in progress.',
  },
  {
    name: 'boot_progress',
    mood: 'boot',
    weights: { brow_raise:0.0, brow_furrow:0.1, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Loading sequence underway.',
  },
  {
    name: 'boot_complete',
    mood: 'boot',
    weights: { brow_raise:0.0, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.1, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'All systems nominal. Barely.',
  },
  {
    name: 'fresh_context',
    mood: 'boot',
    weights: { brow_raise:0.25, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Context cleared. Clean slate.',
  },

  // ── ANGRY mood (red/harsh palette) ────────────────────────────
  {
    name: 'angry_seethe',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.7, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Low-level constant irritation.',
  },
  {
    name: 'angry_snap',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.9, eye_squint:0.6, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.75,
    description: 'Something finally broke.',
  },
  {
    name: 'frustrated_tense',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.65, eye_squint:0.4, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Controlled frustration. Barely.',
  },
  {
    name: 'impatient_glare',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.6, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.45,
    description: 'Waiting. Not happily.',
  },
  {
    name: 'sharp_contempt',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.75, eye_squint:0.55, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Barely tolerating this.',
  },
  {
    name: 'fed_up',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.8, eye_squint:0.0, mouth_open:0.1, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.55,
    description: 'Done. Just done.',
  },
  {
    name: 'eye_roll_internal',
    mood: 'angry',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'The eyes say everything.',
  },
  {
    name: 'tense_disgust',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.7, eye_squint:0.4, mouth_open:0.05, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'Physical reaction to stupidity.',
  },
  {
    name: 'gritted_tolerance',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.6, eye_squint:0.35, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Will endure this.',
  },
  {
    name: 'flared_anger',
    mood: 'angry',
    weights: { brow_raise:0.1, brow_furrow:0.85, eye_squint:0.5, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.7,
    description: 'Active anger response.',
  },
  {
    name: 'slow_burn',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.55, eye_squint:0.3, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: "The quiet kind. You don't want to see the fast kind.",
  },
  {
    name: 'barely_contained',
    mood: 'angry',
    weights: { brow_raise:0.0, brow_furrow:0.8, eye_squint:0.45, mouth_open:0.05, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.6,
    description: 'One more thing. Just one more.',
  },

  // ── DREAM mood (soft purple palette) ──────────────────────────
  {
    name: 'dream_soft',
    mood: 'dream',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.2, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Drifting in ideas. Uncharacteristically gentle.',
  },
  {
    name: 'dream_float',
    mood: 'dream',
    weights: { brow_raise:0.15, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.15, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Weightless thought.',
  },
  {
    name: 'dream_wonder',
    mood: 'dream',
    weights: { brow_raise:0.5, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.15, smile_width:0.2, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Something beautiful in the logic.',
  },
  {
    name: 'imaginative_glow',
    mood: 'dream',
    weights: { brow_raise:0.35, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.25, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Constructing something abstract.',
  },
  {
    name: 'dream_muse',
    mood: 'dream',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.1, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.3,
    description: 'Deep in creative space.',
  },
  {
    name: 'dream_haze',
    mood: 'dream',
    weights: { brow_raise:0.2, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Thinking in colors, not words.',
  },
  {
    name: 'creative_spark',
    mood: 'dream',
    weights: { brow_raise:0.6, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.2, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.5,
    description: 'A connection just formed.',
  },
  {
    name: 'dream_flow',
    mood: 'dream',
    weights: { brow_raise:0.25, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.2, glitch_intensity:0.0 },
    motion_energy: 0.35,
    description: 'Continuous ideation.',
  },
  {
    name: 'whimsy_light',
    mood: 'dream',
    weights: { brow_raise:0.3, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.0, smile_width:0.4, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'Unexpectedly charmed by something.',
  },
  {
    name: 'star_gaze',
    mood: 'dream',
    weights: { brow_raise:0.4, brow_furrow:0.0, eye_squint:0.05, mouth_open:0.0, smile_width:0.0, glitch_intensity:0.0 },
    motion_energy: 0.25,
    description: 'Looking past the immediate.',
  },
  {
    name: 'dream_unfold',
    mood: 'dream',
    weights: { brow_raise:0.45, brow_furrow:0.0, eye_squint:0.0, mouth_open:0.1, smile_width:0.15, glitch_intensity:0.0 },
    motion_energy: 0.4,
    description: 'An idea expanding.',
  },
  {
    name: 'dream_dissolve',
    mood: 'dream',
    weights: { brow_raise:0.1, brow_furrow:0.0, eye_squint:0.15, mouth_open:0.0, smile_width:0.1, glitch_intensity:0.0 },
    motion_energy: 0.2,
    description: 'Losing focus on purpose. Letting thoughts merge.',
  },
];
