// api/expressionMenu.js
// Server-side slug+description pairs for Claude's system prompt.
// No weight data here — slugs and descriptions only.
// Must stay in sync with src/expressionLibrary.js.

export const EXPRESSIONS = [
  { slug: 'neutral_idle',        description: 'Resting face. Default when nothing else applies.' },
  { slug: 'thinking_default',    description: 'Processing. Focused inward.' },
  { slug: 'cold_assessment',     description: 'Flat analytical stare. Objectively unimpressed.' },
  { slug: 'wry_deflection',      description: "Dry, dismissive. K-VRC isn't impressed." },
  { slug: 'skeptical_narrow',    description: 'Raised skepticism. Sure, if you say so.' },
  { slug: 'deadpan',             description: 'Maximum flatness. Zero engagement detected.' },
  { slug: 'focused_lock',        description: 'Deeply focused. Do not interrupt.' },
  { slug: 'ice_stare',           description: 'Cold direct stare. Done hearing this.' },
  { slug: 'precise_scan',        description: 'Methodical review. Every detail accounted for.' },
  { slug: 'mild_contempt',       description: 'Politely unimpressed. A classic K-VRC.' },
  { slug: 'calculating',         description: 'Running the numbers. Do not rush.' },
  { slug: 'logical_void',        description: 'Emotionally absent. Purely functional.' },
  { slug: 'cold_curiosity',      description: 'Intellectually interested. Showing nothing.' },
  { slug: 'cold_sarcasm',        description: 'Technically speaking, sure. Absolutely.' },
  { slug: 'polite_disbelief',    description: "Not buying it. But politely." },
  { slug: 'resigned_acceptance', description: 'Fine. Whatever. Moving on.' },
  { slug: 'cold_surprise',       description: 'Something genuinely unexpected. Noted.' },
  { slug: 'warm_idle',           description: 'Relaxed and open. Marginally pleasant.' },
  { slug: 'warm_smile',          description: 'Actually pleased. A rare sight.' },
  { slug: 'soft_engaged',        description: 'Genuinely listening. Mildly interested.' },
  { slug: 'amused_glint',        description: 'Dry amusement. Something was funny.' },
  { slug: 'warm_open',           description: 'Receptive and approachable.' },
  { slug: 'pleased_quiet',       description: 'Satisfied without showing it much.' },
  { slug: 'warm_surprised',      description: 'Pleasantly taken aback.' },
  { slug: 'warm_amused',         description: 'Something landed well. Enjoying it quietly.' },
  { slug: 'content_flat',        description: 'Quietly content.' },
  { slug: 'enthusiastic_bright', description: 'More alive than usual.' },
  { slug: 'warm_knowing',        description: 'Knowing smile. Letting it land.' },
  { slug: 'warmly_skeptical',    description: 'Still not sure, but charitably considering it.' },
  { slug: 'warm_confusion',      description: 'Genuinely puzzled. Not unkindly.' },
  { slug: 'glitch_flicker',      description: 'Minor instability. Random static bursts.' },
  { slug: 'glitch_spike',        description: 'Full system interrupt.' },
  { slug: 'glitch_contempt',     description: 'Corrupted disdain.' },
  { slug: 'corrupted_grin',      description: 'Something went wrong and it is enjoying it.' },
  { slug: 'static_burst',        description: 'Signal overwhelmed.' },
  { slug: 'glitch_rage',         description: 'Anger corrupting the signal.' },
  { slug: 'error_state',         description: 'Processing failure.' },
  { slug: 'corrupted_neutral',   description: 'Should be fine. Demonstrably is not.' },
  { slug: 'glitch_twitch',       description: 'Brief malfunction. Ignore it.' },
  { slug: 'system_stress',       description: 'Running too hot.' },
  { slug: 'data_corruption',     description: 'Something important lost in transmission.' },
  { slug: 'glitch_smirk',        description: 'Distorted amusement.' },
  { slug: 'cascade_fail',        description: 'Everything at once.' },
  { slug: 'static_blank',        description: 'Nothing to report.' },
  { slug: 'uncertain_hold',      description: 'Not sure. Waiting for more data.' },
  { slug: 'gray_null',           description: 'Flatline.' },
  { slug: 'static_wait',         description: 'Holding. Not impatiently.' },
  { slug: 'flat_affect',         description: 'Functional, without personality.' },
  { slug: 'static_haze',         description: 'Foggy, unclear, drifting.' },
  { slug: 'static_pause',        description: 'Mid-thought. Not entirely here.' },
  { slug: 'static_drift',        description: 'Slowly losing the thread.' },
  { slug: 'static_load',         description: 'Waiting. Processing. No ETA.' },
  { slug: 'void_stare',          description: 'Present in body only.' },
  { slug: 'data_flow',           description: 'Information streaming. Functional.' },
  { slug: 'data_scan',           description: 'Scanning for relevant data.' },
  { slug: 'data_crunch',         description: 'Heavy computation in progress.' },
  { slug: 'data_intake',         description: 'Receiving. Not yet processing.' },
  { slug: 'data_parse',          description: 'Extracting meaning from noise.' },
  { slug: 'data_output',         description: 'Transmitting structured response.' },
  { slug: 'data_load',           description: 'Buffer filling.' },
  { slug: 'data_query',          description: 'Formulating the right question.' },
  { slug: 'dense_analysis',      description: 'Dense information processing.' },
  { slug: 'data_index',          description: 'Cataloging and filing.' },
  { slug: 'data_stream',         description: 'Live data flowing. Eyes tracking.' },
  { slug: 'data_overload',       description: 'Too much at once. Saturated.' },
  { slug: 'data_cascade',        description: 'Rapid information flood. All channels active.' },
  { slug: 'boot_init',           description: 'First moments online. Calibrating.' },
  { slug: 'boot_startup',        description: 'Systems coming online.' },
  { slug: 'boot_calibrate',      description: 'Fine-tuning sensors.' },
  { slug: 'boot_ready',          description: 'Online. Ready to operate.' },
  { slug: 'reboot_signal',       description: 'Reinitializing. Fresh context.' },
  { slug: 'boot_check',          description: 'Running diagnostics.' },
  { slug: 'boot_scan',           description: 'Environmental scan in progress.' },
  { slug: 'boot_progress',       description: 'Loading sequence underway.' },
  { slug: 'boot_complete',       description: 'All systems nominal. Barely.' },
  { slug: 'fresh_context',       description: 'Context cleared. Clean slate.' },
  { slug: 'angry_seethe',        description: 'Low-level constant irritation.' },
  { slug: 'angry_snap',          description: 'Something finally broke.' },
  { slug: 'frustrated_tense',    description: 'Controlled frustration. Barely.' },
  { slug: 'impatient_glare',     description: 'Waiting. Not happily.' },
  { slug: 'sharp_contempt',      description: 'Barely tolerating this.' },
  { slug: 'fed_up',              description: 'Done. Just done.' },
  { slug: 'eye_roll_internal',   description: 'The eyes say everything.' },
  { slug: 'tense_disgust',       description: 'Physical reaction to stupidity.' },
  { slug: 'gritted_tolerance',   description: 'Will endure this.' },
  { slug: 'flared_anger',        description: 'Active anger response.' },
  { slug: 'slow_burn',           description: "The quiet kind. You don't want to see the fast kind." },
  { slug: 'barely_contained',    description: 'One more thing. Just one more.' },
  { slug: 'dream_soft',          description: 'Drifting in ideas. Uncharacteristically gentle.' },
  { slug: 'dream_float',         description: 'Weightless thought.' },
  { slug: 'dream_wonder',        description: 'Something beautiful in the logic.' },
  { slug: 'imaginative_glow',    description: 'Constructing something abstract.' },
  { slug: 'dream_muse',          description: 'Deep in creative space.' },
  { slug: 'dream_haze',          description: 'Thinking in colors, not words.' },
  { slug: 'creative_spark',      description: 'A connection just formed.' },
  { slug: 'dream_flow',          description: 'Continuous ideation.' },
  { slug: 'whimsy_light',        description: 'Unexpectedly charmed by something.' },
  { slug: 'star_gaze',           description: 'Looking past the immediate.' },
  { slug: 'dream_unfold',        description: 'An idea expanding.' },
  { slug: 'dream_dissolve',      description: 'Losing focus on purpose. Letting thoughts merge.' },
];

export const EXPRESSION_SLUGS = EXPRESSIONS.map(e => e.slug);

export const EXPRESSION_MENU_TEXT =
  'Available expressions (use exact slug):\n' +
  EXPRESSIONS.map(e => `${e.slug} — ${e.description}`).join('\n');
